version: '3.1'
services:
  postgres:
    build: ./user-service/database/
    restart: always
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service/database:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:5432
  user-service:
    depends_on:
      - postgres
    build: ./user-service
    restart: unless-stopped
    env_file: ./user-service/.env
    ports:
      - 8080:8080
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
  question-service:
    build: ./question-service
    restart: unless-stopped
    env_file: ./question-service/.env
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - 80:80
