version: "3"
services:
  redis: 
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
  app:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    # image: collaboration-service-app:latest
    container_name: app
    restart: on-failure
    ports:
      - "80:3001"
      - "443:3001"
    volumes:
      - .:/app