name: Node.js CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./question-service
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          MONGO_DB_URL: ${{ secrets.MONGO_DB_URL }}

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
